git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/apps/gworkspace/trunk@23048 72102866-910b-0410-8b05-ffd578937521

diff --git a/Inspector/configure b/Inspector/configure
--- a/Inspector/configure
+++ b/Inspector/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP SH_PATH FILE_PATH have_pdfkit LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os SH_PATH FILE_PATH have_pdfkit LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -829,6 +829,11 @@ Fine tuning of the installation directories:
 _ACEOF
 
   cat <<\_ACEOF
+
+System types:
+  --build=BUILD     configure for building on BUILD [guessed]
+  --host=HOST       cross-compile to build programs to run on HOST [BUILD]
+  --target=TARGET   configure for building compilers for TARGET [HOST]
 _ACEOF
 fi
 
@@ -3010,6 +3015,89 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
           ac_config_headers="$ac_config_headers ContentViewers/ImageViewer/resizer/config.h"
 
 
+# Make sure we can run config.sub.
+$ac_config_sub sun4 >/dev/null 2>&1 ||
+  { { echo "$as_me:$LINENO: error: cannot run $ac_config_sub" >&5
+echo "$as_me: error: cannot run $ac_config_sub" >&2;}
+   { (exit 1); exit 1; }; }
+
+echo "$as_me:$LINENO: checking build system type" >&5
+echo $ECHO_N "checking build system type... $ECHO_C" >&6
+if test "${ac_cv_build+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_build_alias=$build_alias
+test -z "$ac_cv_build_alias" &&
+  ac_cv_build_alias=`$ac_config_guess`
+test -z "$ac_cv_build_alias" &&
+  { { echo "$as_me:$LINENO: error: cannot guess build type; you must specify one" >&5
+echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
+   { (exit 1); exit 1; }; }
+ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_build_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_build" >&5
+echo "${ECHO_T}$ac_cv_build" >&6
+build=$ac_cv_build
+build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+build_vendor=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+echo "$as_me:$LINENO: checking host system type" >&5
+echo $ECHO_N "checking host system type... $ECHO_C" >&6
+if test "${ac_cv_host+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_host_alias=$host_alias
+test -z "$ac_cv_host_alias" &&
+  ac_cv_host_alias=$ac_cv_build_alias
+ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_host_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_host" >&5
+echo "${ECHO_T}$ac_cv_host" >&6
+host=$ac_cv_host
+host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+echo "$as_me:$LINENO: checking target system type" >&5
+echo $ECHO_N "checking target system type... $ECHO_C" >&6
+if test "${ac_cv_target+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_target_alias=$target_alias
+test "x$ac_cv_target_alias" = "x" &&
+  ac_cv_target_alias=$ac_cv_host_alias
+ac_cv_target=`$ac_config_sub $ac_cv_target_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_target_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_target_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_target" >&5
+echo "${ECHO_T}$ac_cv_target" >&6
+target=$ac_cv_target
+target_cpu=`echo $ac_cv_target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+target_vendor=`echo $ac_cv_target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+target_os=`echo $ac_cv_target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+# The aliases save the names the user supplied, while $host etc.
+# will get canonicalized.
+test -n "$target_alias" &&
+  test "$program_prefix$program_suffix$program_transform_name" = \
+    NONENONEs,x,x, &&
+  program_prefix=${target_alias}-
+
 #--------------------------------------------------------------------
 # Debug logging
 #--------------------------------------------------------------------
@@ -3168,30 +3256,55 @@ _ACEOF
 #--------------------------------------------------------------------
 # We need PDFKit
 #--------------------------------------------------------------------
-OLD_CFLAGS=$CFLAGS
-CFLAGS="-xobjective-c"
-PREFIX="-I"
-SUFFIX="Library/Headers/"
-OLD_CPPFLAGS="$CPPFLAGS"
-CPPFLAGS="$CPPFLAGS $PREFIX$GNUSTEP_SYSTEM_ROOT/$SUFFIX $PREFIX$GNUSTEP_LOCAL_ROOT/$SUFFIX"
+case "$target_os" in
+  darwin*)
 
-OLD_LDFLAGS="$LD_FLAGS"
-PREFIX="-L"
-SUFFIX="Library/Libraries/"
-LDFLAGS="$LDFLAGS $PREFIX$GNUSTEP_SYSTEM_ROOT/$SUFFIX $PREFIX$GNUSTEP_LOCAL_ROOT/$SUFFIX"
-OLD_LIBS="$LIBS"
-LIBS="-lgnustep-gui"
-echo "$as_me:$LINENO: checking for PDFKit" >&5
+  echo "$as_me:$LINENO: checking for PDFKit" >&5
+echo $ECHO_N "checking for PDFKit... $ECHO_C" >&6
+  H_SUF="Library/Headers/"
+  PDF_H="PDFKit/PDFDocument.h"
+  PDF_H_PATH="$GNUSTEP_SYSTEM_ROOT/$H_SUF$PDF_H"
+
+  if test -e $PDF_H_PATH; then
+    have_pdfkit=yes
+  else
+    PDF_H_PATH="$GNUSTEP_LOCAL_ROOT/$H_SUF$PDF_H"
+    if test -e $PDF_H_PATH; then
+      have_pdfkit=yes
+    else
+      have_pdfkit=no
+    fi
+  fi
+
+  echo "$as_me:$LINENO: result: $have_pdfkit" >&5
+echo "${ECHO_T}$have_pdfkit" >&6
+
+    ;;
+  *)
+    OLD_CFLAGS=$CFLAGS
+  CFLAGS="-xobjective-c"
+  PREFIX="-I"
+  SUFFIX="Library/Headers/"
+  OLD_CPPFLAGS="$CPPFLAGS"
+  CPPFLAGS="$CPPFLAGS $PREFIX$GNUSTEP_SYSTEM_ROOT/$SUFFIX $PREFIX$GNUSTEP_LOCAL_ROOT/$SUFFIX"
+
+  OLD_LDFLAGS="$LD_FLAGS"
+  PREFIX="-L"
+  SUFFIX="Library/Libraries/"
+  LDFLAGS="$LDFLAGS $PREFIX$GNUSTEP_SYSTEM_ROOT/$SUFFIX $PREFIX$GNUSTEP_LOCAL_ROOT/$SUFFIX"
+  OLD_LIBS="$LIBS"
+  LIBS="-lgnustep-gui"
+  echo "$as_me:$LINENO: checking for PDFKit" >&5
 echo $ECHO_N "checking for PDFKit... $ECHO_C" >&6
 
-cat >conftest.$ac_ext <<_ACEOF
+  cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <Foundation/Foundation.h>
-                  #include <AppKit/AppKit.h>
+                    #include <AppKit/AppKit.h>
 int
 main ()
 {
@@ -3223,28 +3336,28 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   have_pdfkit=yes;
-	gui_found=yes
+	  gui_found=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 have_pdfkit=no;
-	gui_found=no
+	  gui_found=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 
-if test "$gui_found" = "no"; then
-  LIBS="-lgnustep-gui_d"
+  if test "$gui_found" = "no"; then
+    LIBS="-lgnustep-gui_d"
 
-  cat >conftest.$ac_ext <<_ACEOF
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <Foundation/Foundation.h>
-                  #include <AppKit/AppKit.h>
+                    #include <AppKit/AppKit.h>
 int
 main ()
 {
@@ -3276,29 +3389,29 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   have_pdfkit=yes;
-	gui_found=yes
+	  gui_found=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 have_pdfkit=no;
-	gui_found=no
+	  gui_found=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-fi
+  fi
 
-if test "$gui_found" = "no"; then
-  LIBS="-lgnustep-gui_p"
+  if test "$gui_found" = "no"; then
+    LIBS="-lgnustep-gui_p"
 
-  cat >conftest.$ac_ext <<_ACEOF
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <Foundation/Foundation.h>
-                  #include <AppKit/AppKit.h>
+                    #include <AppKit/AppKit.h>
 int
 main ()
 {
@@ -3330,75 +3443,21 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   have_pdfkit=yes;
-	gui_found=yes
+	  gui_found=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 have_pdfkit=no;
-	gui_found=no
+	  gui_found=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-fi
+  fi
 
-GUI_LIBS=$LIBS
+  GUI_LIBS=$LIBS
 
-LIBS="$GUI_LIBS -lPDFKit"
-
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <Foundation/Foundation.h>
-                  #include <AppKit/AppKit.h>
-                  #include <PDFKit/PDFDocument.h>
-int
-main ()
-{
-[PDFDocument class];
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  have_pdfkit=yes;
-	have_pdf_kit=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-have_pdfkit=no;
-	have_pdf_kit=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-
-if test "$have_pdf_kit" = "no"; then
-  LIBS="$GUI_LIBS -lPDFKit_d"
+  LIBS="$GUI_LIBS -lPDFKit"
 
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -3407,8 +3466,8 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <Foundation/Foundation.h>
-                  #include <AppKit/AppKit.h>
-                  #include <PDFKit/PDFDocument.h>
+                    #include <AppKit/AppKit.h>
+                    #include <PDFKit/PDFDocument.h>
 int
 main ()
 {
@@ -3440,30 +3499,29 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   have_pdfkit=yes;
-	have_pdf_kit=yes
+	  have_pdfkit=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 have_pdfkit=no;
-	have_pdf_kit=no
+	  have_pdfkit=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-fi
 
-if test "$have_pdf_kit" = "no"; then
-  LIBS="$GUI_LIBS -lPDFKit_p"
+  if test "$have_pdfkit" = "no"; then
+    LIBS="$GUI_LIBS -lPDFKit_d"
 
-  cat >conftest.$ac_ext <<_ACEOF
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <Foundation/Foundation.h>
-                  #include <AppKit/AppKit.h>
-                  #include <PDFKit/PDFDocument.h>
+                    #include <AppKit/AppKit.h>
+                    #include <PDFKit/PDFDocument.h>
 int
 main ()
 {
@@ -3495,32 +3553,85 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   have_pdfkit=yes;
-	have_pdf_kit=yes
+	  have_pdfkit=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 have_pdfkit=no;
-	have_pdf_kit=no
+	  have_pdfkit=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-fi
+  fi
 
-if test "$have_pdf_kit" = "yes"; then
- echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
+  if test "$have_pdfkit" = "no"; then
+    LIBS="$GUI_LIBS -lPDFKit_p"
+
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Foundation/Foundation.h>
+                    #include <AppKit/AppKit.h>
+                    #include <PDFKit/PDFDocument.h>
+int
+main ()
+{
+[PDFDocument class];
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_pdfkit=yes;
+	  have_pdfkit=yes
 else
- echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+have_pdfkit=no;
+	  have_pdfkit=no
 fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  fi
 
-LIBS="$OLD_LIBS"
-CPPFLAGS="$OLD_CPPFLAGS"
-LDFLAGS="$OLD_LDFLAGS"
-CFLAGS="$OLD_CFLAGS"
+  LIBS="$OLD_LIBS"
+  CPPFLAGS="$OLD_CPPFLAGS"
+  LDFLAGS="$OLD_LDFLAGS"
+  CFLAGS="$OLD_CFLAGS"
 
-if test "$have_pdfkit" = no; then
+  echo "$as_me:$LINENO: result: $have_pdfkit" >&5
+echo "${ECHO_T}$have_pdfkit" >&6
+
+    ;;
+esac
+
+if test "$have_pdfkit" = "no"; then
   { echo "$as_me:$LINENO: The PDFKit framework can't be found." >&5
 echo "$as_me: The PDFKit framework can't be found." >&6;}
   { echo "$as_me:$LINENO: The pdf viewer will not be built." >&5
@@ -4152,6 +4263,18 @@ s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
 s,@CPP@,$CPP,;t t
 s,@EGREP@,$EGREP,;t t
+s,@build@,$build,;t t
+s,@build_cpu@,$build_cpu,;t t
+s,@build_vendor@,$build_vendor,;t t
+s,@build_os@,$build_os,;t t
+s,@host@,$host,;t t
+s,@host_cpu@,$host_cpu,;t t
+s,@host_vendor@,$host_vendor,;t t
+s,@host_os@,$host_os,;t t
+s,@target@,$target,;t t
+s,@target_cpu@,$target_cpu,;t t
+s,@target_vendor@,$target_vendor,;t t
+s,@target_os@,$target_os,;t t
 s,@SH_PATH@,$SH_PATH,;t t
 s,@FILE_PATH@,$FILE_PATH,;t t
 s,@have_pdfkit@,$have_pdfkit,;t t
