* Inspector/configure.ac: * Inspector/configure: * GWMetadata/gmds/configure.ac: * GWMetadata/gmds/configure: Check for GNUSTEP_MAKEFILES, not GNUSTEP_SYSTEM_ROOT * Inspector/aclocal.m4: * GWMetadata/gmds/aclocal.m4: Use GNUSTEP_SYSTEM_HEADERS and GNUSTEP_SYSTEM_LIBRARIES. Remove refernece to obsolete debug and profile extension.
git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/apps/gworkspace/trunk@24642 72102866-910b-0410-8b05-ffd578937521

diff --git a/Inspector/configure b/Inspector/configure
--- a/Inspector/configure
+++ b/Inspector/configure
@@ -1300,9 +1300,9 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-if test -z "$GNUSTEP_SYSTEM_ROOT"; then
-  { { echo "$as_me:$LINENO: error: You must run the GNUstep initialization script first!" >&5
-echo "$as_me: error: You must run the GNUstep initialization script first!" >&2;}
+if test -z "$GNUSTEP_MAKEFILES"; then
+  { { echo "$as_me:$LINENO: error: You must set GNUSTEP_MAKEFILES or run the GNUstep initialization script first!" >&5
+echo "$as_me: error: You must set GNUSTEP_MAKEFILES or run the GNUstep initialization script first!" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -3261,14 +3261,13 @@ case "$target_os" in
 
   echo "$as_me:$LINENO: checking for PDFKit" >&5
 echo $ECHO_N "checking for PDFKit... $ECHO_C" >&6
-  H_SUF="Library/Headers/"
   PDF_H="PDFKit/PDFDocument.h"
-  PDF_H_PATH="$GNUSTEP_SYSTEM_ROOT/$H_SUF$PDF_H"
+  PDF_H_PATH="$GNUSTEP_SYSTEM_HEADERS/$PDF_H"
 
   if test -e $PDF_H_PATH; then
     have_pdfkit=yes
   else
-    PDF_H_PATH="$GNUSTEP_LOCAL_ROOT/$H_SUF$PDF_H"
+    PDF_H_PATH="$GNUSTEP_LOCAL_HEADERS/$PDF_H"
     if test -e $PDF_H_PATH; then
       have_pdfkit=yes
     else
@@ -3281,183 +3280,43 @@ echo "${ECHO_T}$have_pdfkit" >&6
 
     ;;
   *)
-    OLD_CFLAGS=$CFLAGS
+
+
+  GNUSTEP_SH_EXPORT_ALL_VARIABLES=yes
+  . "$GNUSTEP_MAKEFILES/GNUstep.sh"
+  unset GNUSTEP_SH_EXPORT_ALL_VARIABLES
+
+  # For backwards compatibility, define GNUSTEP_SYSTEM_HEADERS from
+  # GNUSTEP_SYSTEM_ROOT if not set yet.
+  if test x"$GNUSTEP_SYSTEM_HEADERS" = x""; then
+    GNUSTEP_SYSTEM_HEADERS="$GNUSTEP_SYSTEM_ROOT/Library/Headers"
+  fi
+  if test x"$GNUSTEP_LOCAL_HEADERS" = x""; then
+    GNUSTEP_LOCAL_HEADERS="$GNUSTEP_LOCAL_ROOT/Library/Headers"
+  fi
+
+  if test x"$GNUSTEP_SYSTEM_LIBRARIES" = x""; then
+    GNUSTEP_SYSTEM_LIBRARIES="$GNUSTEP_SYSTEM_ROOT/Library/Libraries"
+  fi
+  if test x"$GNUSTEP_LOCAL_LIBRARIES" = x""; then
+    GNUSTEP_LOCAL_LIBRARIES="$GNUSTEP_LOCAL_ROOT/Library/Libraries"
+  fi
+
+  OLD_CFLAGS=$CFLAGS
   CFLAGS="-xobjective-c"
   PREFIX="-I"
-  SUFFIX="Library/Headers/"
   OLD_CPPFLAGS="$CPPFLAGS"
-  CPPFLAGS="$CPPFLAGS $PREFIX$GNUSTEP_SYSTEM_ROOT/$SUFFIX $PREFIX$GNUSTEP_LOCAL_ROOT/$SUFFIX"
+  CPPFLAGS="$CPPFLAGS $PREFIX$GNUSTEP_SYSTEM_HEADERS $PREFIX$GNUSTEP_LOCAL_HEADERS"
 
   OLD_LDFLAGS="$LD_FLAGS"
   PREFIX="-L"
-  SUFFIX="Library/Libraries/"
-  LDFLAGS="$LDFLAGS $PREFIX$GNUSTEP_SYSTEM_ROOT/$SUFFIX $PREFIX$GNUSTEP_LOCAL_ROOT/$SUFFIX"
+  LDFLAGS="$LDFLAGS $PREFIX$GNUSTEP_SYSTEM_LIBRARIES $PREFIX$GNUSTEP_LOCAL_LIBRARIES"
   OLD_LIBS="$LIBS"
   LIBS="-lgnustep-gui"
   echo "$as_me:$LINENO: checking for PDFKit" >&5
 echo $ECHO_N "checking for PDFKit... $ECHO_C" >&6
 
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <Foundation/Foundation.h>
-                    #include <AppKit/AppKit.h>
-int
-main ()
-{
-[NSImage class];
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  have_pdfkit=yes;
-	  gui_found=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-have_pdfkit=no;
-	  gui_found=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-
-  if test "$gui_found" = "no"; then
-    LIBS="-lgnustep-gui_d"
-
-    cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <Foundation/Foundation.h>
-                    #include <AppKit/AppKit.h>
-int
-main ()
-{
-[NSImage class];
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  have_pdfkit=yes;
-	  gui_found=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-have_pdfkit=no;
-	  gui_found=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-  fi
-
-  if test "$gui_found" = "no"; then
-    LIBS="-lgnustep-gui_p"
-
-    cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <Foundation/Foundation.h>
-                    #include <AppKit/AppKit.h>
-int
-main ()
-{
-[NSImage class];
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  have_pdfkit=yes;
-	  gui_found=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-have_pdfkit=no;
-	  gui_found=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-  fi
-
-  GUI_LIBS=$LIBS
-
-  LIBS="$GUI_LIBS -lPDFKit"
+  LIBS="$LIBS -lPDFKit"
 
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
@@ -3509,116 +3368,6 @@ have_pdfkit=no;
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-
-  if test "$have_pdfkit" = "no"; then
-    LIBS="$GUI_LIBS -lPDFKit_d"
-
-    cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <Foundation/Foundation.h>
-                    #include <AppKit/AppKit.h>
-                    #include <PDFKit/PDFDocument.h>
-int
-main ()
-{
-[PDFDocument class];
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  have_pdfkit=yes;
-	  have_pdfkit=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-have_pdfkit=no;
-	  have_pdfkit=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-  fi
-
-  if test "$have_pdfkit" = "no"; then
-    LIBS="$GUI_LIBS -lPDFKit_p"
-
-    cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <Foundation/Foundation.h>
-                    #include <AppKit/AppKit.h>
-                    #include <PDFKit/PDFDocument.h>
-int
-main ()
-{
-[PDFDocument class];
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  have_pdfkit=yes;
-	  have_pdfkit=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-have_pdfkit=no;
-	  have_pdfkit=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-  fi
 
   LIBS="$OLD_LIBS"
   CPPFLAGS="$OLD_CPPFLAGS"
