git-svn-id: svn+ssh://svn.gna.org/svn/gnustep/apps/gworkspace/trunk@23085 72102866-910b-0410-8b05-ffd578937521

diff --git a/Tools/gmds/gmds/configure b/Tools/gmds/gmds/configure
--- a/Tools/gmds/gmds/configure
+++ b/Tools/gmds/gmds/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP ADDITIONAL_LIB_DIRS ADDITIONAL_INCLUDE_DIRS have_pdfkit LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT CPP EGREP ADDITIONAL_LIB_DIRS ADDITIONAL_INCLUDE_DIRS have_pdfkit UNZ_PATH LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -851,6 +851,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-sqlite-library=DIR sqlite library files are in DIR
   --with-sqlite-include=DIR sqlite include files are in DIR
+  --with-unzip=PROG  Use PROG as unzip
 
 Some influential environment variables:
   CC          C compiler command
@@ -3089,6 +3090,8 @@ fi
 fi
 
 if test "$have_sqlite" = yes; then
+  sqlite_version_ok=yes
+
   if test "$cross_compiling" = yes; then
   echo "wrong sqlite3 version"
 else
@@ -3131,7 +3134,7 @@ echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-have_sqlite=no
+sqlite_version_ok=no
 fi
 rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
@@ -3152,6 +3155,15 @@ echo "$as_me: WARNING: Cannot find libsqlite3 header and/or library" >&2;}
   { { echo "$as_me:$LINENO: error: The gmds tool will not compile without sqlite" >&5
 echo "$as_me: error: The gmds tool will not compile without sqlite" >&2;}
    { (exit 1); exit 1; }; }
+else
+  if test "$sqlite_version_ok" = no; then
+    { echo "$as_me:$LINENO: WARNING: Wrong libsqlite3 version" >&5
+echo "$as_me: WARNING: Wrong libsqlite3 version" >&2;}
+    echo "* The gmds tool requires libsqlite3 >= 3002008 *"
+    { { echo "$as_me:$LINENO: error: The gmds tool will not compile without sqlite" >&5
+echo "$as_me: error: The gmds tool will not compile without sqlite" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 fi
 
 
@@ -3545,6 +3557,72 @@ fi
 
 
 #--------------------------------------------------------------------
+# We need unzip
+#--------------------------------------------------------------------
+
+# Check whether --with-unzip or --without-unzip was given.
+if test "${with_unzip+set}" = set; then
+  withval="$with_unzip"
+  UNZ_PATH=$withval
+else
+  UNZ_PATH=none
+fi;
+
+if test "x$UNZ_PATH" = "xnone"; then
+	for ac_prog in unzip unzip
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_UNZ_PATH+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $UNZ_PATH in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_UNZ_PATH="$UNZ_PATH" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_UNZ_PATH="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+UNZ_PATH=$ac_cv_path_UNZ_PATH
+
+if test -n "$UNZ_PATH"; then
+  echo "$as_me:$LINENO: result: $UNZ_PATH" >&5
+echo "${ECHO_T}$UNZ_PATH" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$UNZ_PATH" && break
+done
+test -n "$UNZ_PATH" || UNZ_PATH="none"
+
+fi
+
+
+cat >>confdefs.h <<_ACEOF
+#define UNZIP_PATH "$UNZ_PATH"
+_ACEOF
+
+
+#--------------------------------------------------------------------
 # Debug logging
 #--------------------------------------------------------------------
 # Check whether --enable-debug_log or --disable-debug_log was given.
@@ -3567,7 +3645,7 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
-          ac_config_headers="$ac_config_headers config.h"
+                    ac_config_headers="$ac_config_headers config.h ../mdextractor/Extractors/extractors.h"
 
 
                     ac_config_files="$ac_config_files GNUmakefile ../mdextractor/Extractors/GNUmakefile"
@@ -4100,6 +4178,7 @@ do
   "GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES GNUmakefile" ;;
   "../mdextractor/Extractors/GNUmakefile" ) CONFIG_FILES="$CONFIG_FILES ../mdextractor/Extractors/GNUmakefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
+  "../mdextractor/Extractors/extractors.h" ) CONFIG_HEADERS="$CONFIG_HEADERS ../mdextractor/Extractors/extractors.h" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -4208,6 +4287,7 @@ s,@EGREP@,$EGREP,;t t
 s,@ADDITIONAL_LIB_DIRS@,$ADDITIONAL_LIB_DIRS,;t t
 s,@ADDITIONAL_INCLUDE_DIRS@,$ADDITIONAL_INCLUDE_DIRS,;t t
 s,@have_pdfkit@,$have_pdfkit,;t t
+s,@UNZ_PATH@,$UNZ_PATH,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3373,6 +3373,8 @@ fi
 fi
 
 if test "$have_sqlite" = yes; then
+  sqlite_version_ok=yes
+
   if test "$cross_compiling" = yes; then
   echo "wrong sqlite3 version"
 else
@@ -3415,7 +3417,7 @@ echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 ( exit $ac_status )
-have_sqlite=no
+sqlite_version_ok=no
 fi
 rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
@@ -3432,6 +3434,15 @@ echo "$as_me: WARNING: Cannot find libsqlite3 header and/or library" >&2;}
   { { echo "$as_me:$LINENO: error: GWorkspace will not compile without sqlite" >&5
 echo "$as_me: error: GWorkspace will not compile without sqlite" >&2;}
    { (exit 1); exit 1; }; }
+else
+  if test "$sqlite_version_ok" = no; then
+    { echo "$as_me:$LINENO: WARNING: Wrong libsqlite3 version" >&5
+echo "$as_me: WARNING: Wrong libsqlite3 version" >&2;}
+    echo "* GWorkspace requires libsqlite3 >= 3002008 *"
+    { { echo "$as_me:$LINENO: error: GWorkspace will not compile without sqlite" >&5
+echo "$as_me: error: GWorkspace will not compile without sqlite" >&2;}
+   { (exit 1); exit 1; }; }
+  fi
 fi
 
 #--------------------------------------------------------------------
